# Generated by Django 4.1.4 on 2022-12-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=1, max_digits=5)),
                ('y', models.DecimalField(decimal_places=1, max_digits=5)),
                ('z', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
    ]
