# Generated by Django 4.1.4 on 2022-12-14 21:25

from django.db import migrations, models
import django.contrib.postgres.fields



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', django.contrib.postgres.fields.ArrayField(models.DecimalField(decimal_places=1, max_digits=5))),
                ('y', django.contrib.postgres.fields.ArrayField(models.DecimalField(decimal_places=1, max_digits=5))),
                ('z', django.contrib.postgres.fields.ArrayField(models.DecimalField(decimal_places=1, max_digits=5))),
            ],
        ),
    ]
