# Generated by Django 4.1.4 on 2022-12-30 15:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_points_spring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='x',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=5), size=None),
        ),
        migrations.AlterField(
            model_name='points',
            name='y',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=5), size=None),
        ),
        migrations.AlterField(
            model_name='points',
            name='z',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=5), size=None),
        ),
    ]
