# Generated by Django 4.1.4 on 2022-12-30 15:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_alter_points_x_alter_points_y_alter_points_z'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points',
            name='y',
        ),
        migrations.RemoveField(
            model_name='points',
            name='z',
        ),
        migrations.AlterField(
            model_name='points',
            name='x',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None),
        ),
    ]
