# Generated by Django 4.1.4 on 2022-12-30 16:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_alter_points_x_alter_points_y_alter_points_z'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='esf',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=5), default=[], size=None),
        ),
    ]
