# Generated by Django 4.1.4 on 2022-12-30 15:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_remove_points_y_remove_points_z_alter_points_x'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='y',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=5), default=[1, 2], size=None),
        ),
        migrations.AddField(
            model_name='points',
            name='z',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=5), default=[1, 2], size=None),
        ),
    ]
