# Generated by Django 4.1.4 on 2022-12-30 16:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_points_esf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points',
            name='x',
        ),
        migrations.RemoveField(
            model_name='points',
            name='y',
        ),
        migrations.RemoveField(
            model_name='points',
            name='z',
        ),
        migrations.AddField(
            model_name='points',
            name='posx',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=5), default=[], size=None),
        ),
        migrations.AddField(
            model_name='points',
            name='posy',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=5), default=[], size=None),
        ),
        migrations.AddField(
            model_name='points',
            name='posz',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=5), default=[], size=None),
        ),
    ]
