# Generated by Django 4.1.4 on 2022-12-14 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alambre', models.DecimalField(decimal_places=2, max_digits=4)),
                ('diam', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vueltas', models.DecimalField(decimal_places=3, max_digits=6)),
                ('longitud', models.DecimalField(decimal_places=2, max_digits=6)),
                ('luz1', models.IntegerField()),
                ('luz2', models.IntegerField()),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.points')),
            ],
        ),
    ]
